server:
  port: 8080

spring:
  application:
    name: bug
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8080
      fail-fast: true
      #retry:
        #initial-interval: 1500
        #max-attempts: 6
        #max-interval: 15000
        #multiplier: 1.2
  profiles:
    active: dev

management:
  endpoints:
    web:
      base-path: /v1/actuator
    exposure:
      include: health, info
