server:
  port: 8080

spring:
  application:
    name: bug
  config:
    import: "configserver:"
  cloud:
    config:
      uri: https://github.com/kevindeyne-ab/sample-config-repo.git
  profiles:
    active: dev

management:
  endpoints:
    web:
      base-path: /v1/actuator
    exposure:
      include: health, info
